<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="baseValueType">
    <xs:sequence>
      <xs:element name="num" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="specialValueType">
    <xs:sequence>
      <xs:element name="num" type="xs:integer"/>
      <xs:element name="tag" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="holder" type="baseValueType"/>

  <xs:element name="container">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" type="baseValueType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
