<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="code" type="xs:token"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="order" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="line" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="ref" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:key name="itemKey">
      <xs:selector xpath="item"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:unique name="itemCode">
      <xs:selector xpath="item"/>
      <xs:field xpath="code"/>
    </xs:unique>
    <xs:keyref name="orderRef" refer="itemKey">
      <xs:selector xpath="order/line"/>
      <xs:field xpath="@ref"/>
    </xs:keyref>

  </xs:element>

</xs:schema>
